mode: 3

# Engine Build Parameters
onnx_file: "models/realesrgan_general_x4v3_f16.onnx"
plan_file: "models/realesrgan_general_x4v3_f16.plan"
max_batch: 16
opt_batch: 16
min_batch: 16
workspace: 268435456  # 256 MB
strongly_typed: true

# Input Settings
input: "/mnt/d/raw_videos/motorcycle.yuv"
input_format: "i420"
input_full_range: 1

# Output Settings
output: "output.yuv"
output_width: 1920
output_height: 1080
output_format: "i420"
output_full_range: 1

# Processing Parameters
prescale: 1.0
overlap: 4
batches: 16
